#!/bin/bash

# Print all commands executed if DEBUG mode enabled
[ -n "${DEBUG:-""}" ] && set -x

config_dir="${PRYSM_CONFIG_DIR:-/etc/prysm}"
config_path="${config_dir}/config.yml"

mkdir -p $config_dir

# customize config based on set "CONFIG_<setting>" environment variables
prysm-helper config customize --config-path $config_path
